"""Synthetic demonstration records for the local evaluator."""

from __future__ import annotations

from typing import Any


def demo_locus_records() -> list[dict[str, Any]]:
    """Return clearly synthetic LOCUS-like records covering evaluator paths."""

    return [
        {
            "header": "Synthetic Chapter 1: Purpose",
            "content": "SYNTHETIC DEMONSTRATION DATA. Sample Valley explains the purpose of its code and includes no operative rule.",
            "is_substantive": False,
            "function": "Context",
            "topic": None,
            "source_jurisdiction_type": "cities",
            "state": "ny",
            "city": "Sample Valley",
            "county": None,
            "enforcement_discretion": 0.10,
            "opacity": 0.20,
            "paternalism": 0.15,
            "problem_salience": 0.30,
        },
        {
            "header": "Synthetic Zoning Permit Rule",
            "content": "SYNTHETIC DEMONSTRATION DATA. Example Township requires a zoning permit before construction begins. The official may request additional plans.",
            "is_substantive": True,
            "function": "Rules",
            "topic": "Zoning",
            "source_jurisdiction_type": "cities",
            "state": "PA",
            "city": "Example Township",
            "county": "Demo County",
            "enforcement_discretion": 0.62,
            "opacity": 0.48,
            "paternalism": 0.35,
            "problem_salience": 0.71,
        },
        {
            "header": "Synthetic Business License Process",
            "content": "SYNTHETIC DEMONSTRATION DATA. Synthetic Vendor LLC must file a renewal form by March 1 and pay the listed fee.",
            "is_substantive": True,
            "function": "Process",
            "topic": "Business",
            "source_jurisdiction_type": "cities",
            "state": "tx",
            "city": "Demo City",
            "county": None,
            "enforcement_discretion": 0.24,
            "opacity": 0.41,
            "paternalism": 0.18,
            "problem_salience": 0.52,
        },
        {
            "header": "Synthetic County Nuisance Enforcement",
            "content": "SYNTHETIC DEMONSTRATION DATA. Demo County may issue a notice for repeated nuisance conditions!!!!",
            "is_substantive": True,
            "function": "Enforcement",
            "topic": "Nuisance",
            "source_jurisdiction_type": "counties",
            "state": "CA",
            "city": None,
            "county": "Demo County",
            "enforcement_discretion": 0.83,
            "opacity": 0.55,
            "paternalism": 0.43,
            "problem_salience": 0.68,
        },
        {
            "header": "Synthetic Broken OCR",
            "content": "SYNTHETIC DEMONSTRATION DATA. �� Sec. 4 -- -- -- text text text",
            "is_substantive": True,
            "function": "Structural",
            "topic": "Buildings",
            "source_jurisdiction_type": "special district",
            "state": "n y",
            "city": None,
            "county": None,
            "enforcement_discretion": float("nan"),
            "opacity": 1.2,
            "paternalism": None,
            "problem_salience": 0.2,
        },
        {
            "header": "Synthetic Short",
            "content": "SYNTHETIC DEMONSTRATION DATA. Fee.",
            "is_substantive": False,
            "function": "Rules",
            "topic": "Other",
            "source_jurisdiction_type": "cities",
            "state": "FL",
            "city": "",
            "county": "",
            "enforcement_discretion": 0.0,
            "opacity": 0.0,
            "paternalism": 0.0,
            "problem_salience": 0.0,
        },
    ]
